#---------------------------
# Hexo Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# Docsï¼šhttps://hexo.fluid-dev.com/docs/guide/
#---------------------------


#---------------------------
# Site
#---------------------------
favicon: /img/favicon.ico

apple_touch_icon: /img/favicon.ico

title_join_string: ' - '

force_https: false

code:
  copy_btn: true
  highlight: 
    enable: true
    lib: 'highlightjs'
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: 'default'
      preprocess: true

fun_features:
  typing:
    enable: false
    typeSpeed: 70
    cursorChar: "_"
    loop: false
  anchorjs:
    enable: false
    element: h1,h2,h3,h4
    placement: right
    visible: always
    icon: "â¡"
  mouse_click:
    enable: false
    style: values

dark_mode:
  enable: true
  default: light

color:
  body_bg_color: "#eee"
  body_bg_color_dark: "#181c27"
  navbar_bg_color: "#2f4154"
  navbar_bg_color_dark: "#1f3144"
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"
  board_color: "#fff"
  board_color_dark: "#252d38"

font:
  font_size: 16px
  font_family:
  code_font_size: 85%

custom_js:
custom_css:
custom_html: ''

web_analytics:
  enable: false
  baidu:
  google:
  gtag:
  tencent:
    sid:
    cid:
  woyaola:
  cnzz:
  leancloud:
    app_id:
    app_key:
    server_url:

lazyload:
  enable: false
  onlypost: false

daovoice:
  enable: false
  appid: ''

aplayer:
  enable: false
  autoplay: false
  loop: 'all'
  order: 'random'
  theme: '#b7daff'
  songs:
    - { name: 'name', artist: 'artist', url: '/songs/test.mp3', cover: '/img/cover.jpg' }
    - { name: 'name', artist: 'artist', url: 'https://...url.mp3', cover: 'https://...cover.jpg' }

version:
  check: false


#---------------------------
# Header
#---------------------------
navbar:
  blog_title:
  ground_glass:
    enable: false
    px: 3
    alpha: 0.7
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }

search:
  enable: false
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true

scroll_down_arrow:
  enable: true
  banner_height_limit: 90
  scroll_after_turning_page: true

banner_parallax: true


#---------------------------
# Footer
#---------------------------
footer:
  statistics:
    enable: false
    source: "busuanzi"
    pv_format: "Total {} times"
    uv_format: "Total {} people"

  beian:
    enable: false
    icp_text:
    police_text:
    police_code:
    police_icon:

scroll_top_arrow:
  enable: true


#---------------------------
# Index Page
#---------------------------
index:
  banner_img: /img/default.jpg
  banner_img_height: 100  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  post_default_img:
  slogan:
    enable: true
    text:
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: true


# Custom Page
page:
  banner_img: /img/default.jpg
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0


#---------------------------
# Post Page
#---------------------------
post:
  banner_img: /img/default.jpg
  banner_img_height: 90  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  meta:
    author:
      enable: false
    date:
      enable: true
      format: "YYYY-MM-DD"
    wordcount:
      enable: true
      format: "{} words"
    min2read:
      enable: true
      format: "{} minutes"
      words: 60
    views:
      enable: false
      source: "busuanzi"
      format: "{} times"
  updated:
    enable: false
    content: 'Last update at:'
    relative: false
  toc:
    enable: true
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 1
  copyright:
    enable: true
    content: 'Copyright (c) 2020 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE'
  prev_next:
    enable: true
  custom:
    enable: false
    content: ''
  image_zoom:
    enable: false
  footnote:
    enable: true
    header: ''
  math:
    enable: false
    specific: true
    engine: mathjax
  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }
  comments:
    enable: false
    type: disqus


#---------------------------
# Comments
#---------------------------
utterances:
  repo:
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark
  crossorigin: anonymous

disqus:
  shortname:
  disqusjs: false
  apikey:

gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  admin: ['name']
  id: location.pathname
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true

valine:
  appid:
  appkey:
  placeholder:
  path: window.location.pathname
  avatar: retro
  meta: ['nick', 'mail', 'link']
  pageSize: 10
  lang: zh-cn
  highlight: false
  recordIP: false
  serverURLs:

changyan:
  appid: ''
  appkey: ''

livere:
  uid: ''

remark42:
  host: https://remark.haoyizebo.com
  site_id: haoyizebo
  max_shown_comments: 10
  locale: zh


#---------------------------
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.jpg
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 'Archive'

#---------------------------
# Categories Page
#---------------------------
category:
  banner_img: /img/default.jpg
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 'Category'
  post_limit: 10
  order_by: '-length'
  collapse_depth: 1

#---------------------------
# Tags Page
#---------------------------
tag:
  banner_img: /img/default.jpg
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 'Tags'
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# About Page
#---------------------------
about:
  banner_img: /img/default.jpg
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 'Always Keep Calm And Believe Yourself.'
  avatar: /img/avatar.jpeg
  name: AimerNeige
  introduce: 'Programming beginner from China.'
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/AimerNeige/', tip: 'GitHub' }


#---------------------------
# 404 Page
#---------------------------
page404:
  banner_img: /img/default.jpg
  banner_img_height: 85  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 'Page not found'


#---------------------------
# Links Page
#---------------------------
links:
  banner_img: /img/default.jpg
  banner_img_height: 60  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: Friends
  items:
    - {
      title: 'ä¼',
      intro: 'ä¸€åªå’¸é±¼çš„å­¦ä¹ è®°å½•',
      link: 'https://farewell12345.github.io/',
      image: 'https://farewell12345.github.io/farewell12345.github.io/img/HEAD.png'
    }
    - {
      title: 'HelloWorldçš„å°åšå®¢',
      intro: 'è¿™é‡Œæ˜¯ä¸€ä¸ªå°ç™½çš„åšå®¢',
      link: 'https://mzdluo123.github.io/',
      image: 'https://avatars0.githubusercontent.com/u/23146087?s=400&v=4'
    }
    - {
      title: 'TangZ',
      intro: 'TangZ çš„ä¸ªäººé¡µé¢',
      link: 'https://wstzj.github.io/',
      image: 'https://raw.githubusercontent.com/wstzj/picGo/master/img/1.jpg'
    }
    - {
      title: 'Kenvix',
      intro: 'å…šæ˜å­¦å§',
      link: 'https://kenvix.com/',
      image: 'https://secure.gravatar.com/avatar/11804ec6b3178d7f4ada6177d224de2d?s=112&d=mm'
    }
    - {
      title: 'Dreace',
      intro: 'ä¸­åŒ—ä¿¡æ¯å¼€å‘è€…',
      link: 'https://blog.dreace.top/',
      image: 'https://cdn.jsdelivr.net/gh/dreace/dreace.github.io@master/images/avatar.png'
    }
    - {
      title: 'é¸¢å°¾èŠ±å¼€',
      intro: 'æµ©äºŒå…ˆè¾ˆ',
      link: 'http://ishero.net/',
      image: 'https://avatars3.githubusercontent.com/u/29891793?s=460&v=4'
    }
    - {
      title: 'ğŸ”¨',
      intro: 'ğŸ”¨ã®Blog',
      link: 'https://geekhe-p.github.io/',
      image: 'https://cdn.jsdelivr.net/gh/geekHe-P/PicGo/article/7a2cb9f60c2846322890b138ae849557.jpeg'
    }
    - {
      title: 'Gaein nidb',
      intro: 'Gaein nidbçš„ç½‘ç«™',
      link: 'https://www.gaein.cn/',
      image: 'https://avatars2.githubusercontent.com/u/36162655?s=460&u=69b5ab41907989a57572a63bea23eccf47203d8d&v=4'
    }
    - {
      title: '0047ol',
      intro: 'æ•´åˆç¨€ç¼ºè½¯ä»¶ä»“åº“',
      link: 'https://www.0047ol.com/',
      image: 'https://raw.githubusercontent.com/aimerneige/PicGoData/master/img/047.png'
    }
    - {
      title: 'vritser',
      intro: 'åŠæ–¤å…«ä¸¤',
      link: 'https://vritser.github.io/',
      image: 'https://avatars3.githubusercontent.com/u/16340478?s=400&u=d35db0b9c626e1464692dbb189dbf98e1ab80dd6&v=4'
    }
    # - {
    #   title: 'Nios34',
    #   intro: 'Nios34 çš„ä¸ªäººé¡µé¢',
    #   link: 'http://ftp.ski/',
    #   image: 'https://raw.githubusercontent.com/AimerNeige/PicGoData/master/img/Nios34.png'
    # }